### ISSUE TITLE
Need help with compiling

### ISSUE THREAD

**Issue by micwoj92** [eyeCube/Softly-Roguelike#2]
I tried to compile this and got error
ModuleNotFoundError: No module named 'scipy'
So i installed python-scipy (should probably be added to requirements.txt) and tried to compile again, then I got another error, pasting whole build log below
 [micwoj92@desktop]: ~/Desktop/test_xd/Softly-Roguelike/src>$ python main.py
missing ID # 70 in IDENTIFICATION
(previous is ('pants', 33))
missing ID # 116 in IDENTIFICATION
(previous is ('flower', 6))
missing ID # 119 in IDENTIFICATION
(previous is ('root', 6))
missing ID # 132 in IDENTIFICATION
(previous is ('bipod', 38))
False
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    import rogue as rog
  File "/home/micwoj92/Desktop/test_xd/Softly-Roguelike/src/rogue.py", line 34, in <module>
    import entities
  File "/home/micwoj92/Desktop/test_xd/Softly-Roguelike/src/entities.py", line 6488, in <module>
    'metal Allen wrench'    :(8,    0.1, 300, METL,1, 8, (0,  1,  2,  0,  0,  0,  0,  1,  -12,0,  4,  0,  -20,0, 0,),None,_allenwrench,ID_TOOL,),
NameError: name 'ID_TOOL' is not defined 

Could you please help? My os is arch linux.

**Comment by micwoj92** [comment]
[micwoj92@desktop]: ~/Desktop/test_xd/Softly-Roguelike/src>$ python main.py
missing ID # 70 in IDENTIFICATION
(previous is ('pants', 33))
missing ID # 116 in IDENTIFICATION
(previous is ('flower', 6))
missing ID # 119 in IDENTIFICATION
(previous is ('root', 6))
missing ID # 132 in IDENTIFICATION
(previous is ('bipod', 38))
False
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    import rogue as rog
  File "/home/micwoj92/Desktop/test_xd/Softly-Roguelike/src/rogue.py", line 34, in <module>
    import entities
  File "/home/micwoj92/Desktop/test_xd/Softly-Roguelike/src/entities.py", line 6488, in <module>
    'metal Allen wrench'    :(8,    0.1, 300, METL,1, 8, (0,  1,  2,  0,  0,  0,  0,  1,  -12,0,  4,  0,  -20,0, 0,),None,_allenwrench,ID_TOOL,),
NameError: name 'ID_TOOL' is not defined

**Comment by eyeCube** [comment]
Sorry for the delayed response. I'm returning to this project with the goal of finishing it now. If anyone is curious, this problem should be fixed now.

**Comment by micwoj92** [comment]
This seems to be fixed, now I am getting different error as of https://github.com/eyeCube/Softly-Roguelike/commit/a253651713a50b14700a04ca20998632ff26e5e9
```
Traceback (most recent call last):
  File "/home/micwoj92/Desktop/test_xd/Softly-Roguelike/src/main.py", line 27, in <module>
    import rogue as rog
  File "/home/micwoj92/Desktop/test_xd/Softly-Roguelike/src/rogue.py", line 34, in <module>
    import components as cmp
  File "/home/micwoj92/Desktop/test_xd/Softly-Roguelike/src/components.py", line 1503
    __slots__=['energy','mats','tools']
                                       ^
IndentationError: unindent does not match any outer indentation level

```
